FROM node:latest AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install -g npm@latest

COPY . .

RUN npx prisma generate

RUN npm run build

FROM node:latest AS runner

WORKDIR /app

ENV NODE_ENV=${NODE_ENV} \
    PORT=3001 \
    DATABASE_URL=${DATABASE_URL} \
    MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD} 

COPY --chown=node:node package*.json ./

COPY --from=builder /app/dist/ ./dist

RUN npm install --omit dev

USER node

EXPOSE 3001

CMD ["npm", "run", "start"]