name: scipBackend
services:
  api: 
    container_name: scipBackend 
    build: .\
    env_file:
      - .env
    ports:
     - "3001-3001"
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=notes-db 
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: